//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CitasMedicasEntities : DbContext
    {
        public CitasMedicasEntities()
            : base("name=CitasMedicasEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Medicos> Medicos { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
    
        public virtual ObjectResult<SP_PACIENTES_CITAS_MEDICOS_Result> SP_PACIENTES_CITAS_MEDICOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PACIENTES_CITAS_MEDICOS_Result>("SP_PACIENTES_CITAS_MEDICOS");
        }
    }
}
